### ISSUE TITLE
Errors appear when navigating in the settings

### ISSUE THREAD

**Issue by EvaisaDev** [DrBibop/RoR2VRMod#28]
You cannot access the risk of options menu in vr, when using the triggers to move through the tabs it stops at the VR tab and starts throwing errors into the console.
Maybe I am missing something but I assume there just isn't any compatibility right now.

**Comment by DrBibop** [comment]
The only options in there are recenter binds but I was not aware of any errors when reaching that page. Can you join the Discord server linked in the mod page and explain these errors to me?

**Comment by DrBibop** [comment]
Editing this issue for the errors appearing but the last tab being unaccessible is the other mod's fault.
