### ISSUE TITLE
HMD renders gray screen when using controllers that do not match the HMD.

### ISSUE THREAD

**Issue by Terbz** [DrBibop/RoR2VRMod#32]
I have a Reverb G2 that I use with Knuckles. The game will load and I will have full range of motion, but I can only see the gameplay on my monitor, the headset will render nothing but a gray screen. This does not occur if only the G2 controllers are turned on, but will instantly change the second the Knuckles are turned on.

**Comment by DrBibop** [comment]
I looked into this and it seems to be a common WMR/SteamVR issue with stationary/seated VR games. I can try to set the mod as a "roomscale" game but this will prevent me from using certain features such as recentering.
