### ISSUE TITLE
View tilted to the left, controllers don't move

### ISSUE THREAD

**Issue by AmyTheCute** [DrBibop/RoR2VRMod#36]
![Screenshot (1115)](https://user-images.githubusercontent.com/44164611/119809612-89ec5380-befa-11eb-8ff2-03881c0bc425.png)
my console has this error. I'm using an oculus quest 2 via LINK.

when I start the game my controller inputs work but moving them doesn't move the in-game controller i can barely see on the left of my field of vision.

everything is tilted towards left. most of the right side of my screen is black, and I see a window on the left of my field of vision that follows my head,

**Comment by DrBibop** [comment]
Please ask for help in the Discord server before creating a new issue. I will attempt to help you there.
