### ISSUE TITLE
Equipment failing to activate

### ISSUE THREAD

**Issue by ryocryte** [DrBibop/RoR2VRMod#40]
Was using Royal Capacitor and while it was off cooldown, I was only sometimes able to use it. I would press the bottom button on my left controller and it would not activate about half of the time I would try. I was unable to figure out why, it seemed to be random. I was using the Oculus Rift S, I had the mod in Oculus mode and I was on Vanilla, no other mods. Did not seem to have this issue with other equipment, it may be an issue with equipments that target something.

**Comment by DrBibop** [comment]
Please report potential bugs in the discord server instead of opening an issue. I need to make sure there is indeed a bug and if there is an easy way to reproduce it. https://discord.gg/ZFSCSDe
