### ISSUE TITLE
unable to open chat

### ISSUE THREAD

**Issue by cubiclestorm** [DrBibop/RoR2VRMod#59]
Whenever I press enter I get this red text in the BepinEx console making joining a game in progress impossible:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.UI.CursorOpener.RebuildLinks () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0017)
RoR2.UI.CursorOpener.set_opening (System.Boolean value) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0011)
RoR2.UI.CursorOpener.OnDisable () (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_0000)
UnityEngine.GameObject:SetActive(Boolean)
RoR2.UI.ChatBox:set_showInput(Boolean)
RoR2.UI.ChatBox:Update()

**Comment by DrBibop** [comment]
Hello!

I am no longer using issues to manage bugs and features.
Please report bugs in our Discord server here: https://discord.gg/ZFSCSDe
Grab the Risk of Rain 2 role and I will be able to help you there.
