### ISSUE TITLE
SteamVR Error

### ISSUE THREAD

**Issue by DrekAnon** [DrBibop/RoR2VRMod#60]
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'SteamVR, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2cc17dca390941eeb4d7b2ff1f84696a>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
VRMod.VRMod:<Awake>b__2_0()
RoR2.<OnLoad>d__60:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by DrekAnon** [comment]
Didn't load SteamVR on open

**Comment by DrBibop** [comment]
This usually happens when you have game theatre enabled. Let me know if disabling it fixed it.
