### ISSUE TITLE
Won't load?

### ISSUE THREAD

**Issue by KitBallard64** [DrBibop/RoR2VRMod#61]
Unsure if it's not loading cause it's not updated for the newest patch, or I'm just not doing som'in right but uhm... yeah.. I can't get this mod to load. I hope it's just needing an update to run for the newer version and I just need to wait~♪

~Kito

**Comment by DrBibop** [comment]
Thats basically it, yeah. I was busy last week but I should be able to patch the mod within the following few days.

**Comment by KitBallard64** [comment]
Ah ok! I appreciate hearing that and sorry to of bothered ya. Good luck! I look forward to when it's available ^_^

~Kito
