### ISSUE TITLE
"Use controller direction for movement" setting does not affect vertical movement

### ISSUE THREAD

**Issue by AmadeusMop** [DrBibop/RoR2VRMod#64]
When flying with a Milky Chrysalis, controller direction only affects horizontal orientation (yaw), while vertical orientation (pitch) is still controlled by headset. This makes it very difficult to fly up while shooting down.

**Comment by DrBibop** [comment]
Will add it to the Tello. Thank you!

**Comment by AmadeusMop** [comment]
[I found this issue annoying enough that I decided to attempt a fix myself](https://github.com/DrBibop/RoR2VRMod/pull/65)
