### ISSUE TITLE
Smooth Turning & Sitting Offset

### ISSUE THREAD

**Issue by SingStarAt60Frames** [DrBibop/RoR2VRMod#67]
Just some general normal concerns regarding VR.

1)Is there a way to toggle Smooth Turning instead of Snap Turning?

2)Readjustment option for sitting? Felt awfully short even with the camera adjustment while sitting. Is there a way to fix that too?

**Comment by DrBibop** [comment]
You can disable snap turn in the VR settings. Did you enable seated mode? Keep in mind that changing that setting requires a restart of the game.
