### ISSUE TITLE
xsplitscreen support

### ISSUE THREAD

**Issue by T0knd** [DrBibop/RoR2VRMod#69]
I was trying to play the vr mod with xsplitscreen, but it wasn't working as I thought it would. I understand that it's on the other modder to make it vr compatable, but I also would really want to play it while my friend is playing---both in vr. 

Thanks for the consideration

-fellow vr ROR2 enjoyer

**Comment by DrBibop** [comment]
I highly doubt that this is possible. I don't even think there's a real VR game out there with a similar feature. Not to mention that rendering on two headsets at the same time using the same computer would probably explode your GPU lol. Your friend needs their own computer and copy of RoR2.
