### ISSUE TITLE
add first person

### ISSUE THREAD

**Issue by coolcourd** [DrBibop/RoR2VRMod#7]
There is a first-person mod https://thunderstore.io/package/mistername/FirstPersonView/
but it doesn't recognize the head movement when determining walking left, right, forward, back. so, you want to keep your head straight and aim with the controller, just feels weird in vr.  It would be nice to have a working first person option available and perhaps default.

**Comment by DrBibop** [comment]
I share the same feeling. I remember throwing the idea not long ago and I do think it would be a great addition. I’ll see if I can make it happen in a future update
